blank_issues_enabled: false

contact_links:
  - name: 📌 HYU UMC 9th Node.js 이슈 가이드
    url: https://github.com/HSU-Makeus-Challenge-9th/Node.js/issues
    about: 일반적인 문의나 버그 리포트 전에 이슈 가이드를 확인해주세요.

issue_templates:
  - name: 🐞 버그 리포트
    description: 버그를 신고하고 수정 요청을 작성하세요.
    file: bug_report.md

  - name: ✨ 기능 요청
    description: 새로운 기능을 제안하세요.
    file: feature_request.md

  - name: ♻️ 리팩토링
    description: 코드 개선 및 리팩토링을 제안하세요.
    file: refactor.md
